thin-provisioning-tools: Fix building with ToT libc++
Fix build failures related to size_t:

persistent-data/hex_dump.h:27:53: error: unknown type name 'size_t'
 void hex_dump(std::ostream &out, void const *data, size_t len);

This fixed building with latest libc++ which has removed an implicit
include of <cstddef> when including <iosfwd>, b/280694694.
The patch can't be sent upstream as the upstream has moved
to a rust based implementation.

BUG=b:280694694
TEST=emerge thin-provisioning-tools with llvm tot

Change-Id: I412087c7f23d19c3f4e4b1d55f26d9c0a4d89b3a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4505012
Auto-Submit: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Denis Nikitin <denik@chromium.org>
Reviewed-by: Sergey Frolov <sfrolov@google.com>