dev-python/cffi: Add a missing dependency
Fix the compile error caused by missing Python.h.

c/_cffi_backend.c:2:10: fatal error: 'Python.h' file not found
         ^~~~~~~~~~
	 1 error generated.

BUG=b:273159126
TEST=BOARD=amd64-generic bazel build @portage//dev-python/cffi

Original-Change-Id: I86c499b9f6a4a95107b5fa1fb479a13cb4f3617f
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/portage-stable/+/1785288
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit b1f4976c330cd88599dc3e007d101dc13c146da0)

Link: https://github.com/gentoo/gentoo/pull/30469

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//dev-python/cffi

Change-Id: I5567162269dc99b5e1ebbd139452a32a1d8ab093
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4396131
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>