eclass/distutils-r1: Add PYTHON_DEPS to DEPEND unconditionally
Python distutils packages that build C extensions are currently not
declaring PYTHON_DEPS as part of their DEPEND declaration. This results
in build errors when cross compiling using ROOT=.

i.e.,
   In file included from src/setproctitle.c:14:
   In file included from src/spt.h:15:
   src/spt_python.h:15:10: fatal error: 'Python.h' file not found
   #include <Python.h>
            ^~~~~~~~~~
   1 error generated.

Since the distutils-r1 eclass currently sets the RDEPEND and BDEPEND
variables it makes sense to have the eclass also set the DEPEND
variable. We unconditionally add it to keep the API simple. If in the
future this is problematic, we can maybe add a DISTUTILS_PURE_PYTHON
eclass variable that will omit the DEPEND.

BUG=b:262460834
TEST=BOARD=amd64-generic bazel build -k --config=prebuilts/amd64-generic  --//bazel/sdk:new-sdk @portage//virtual/target-os-test:all

Link:https://github.com/gentoo/gentoo/pull/30469
Change-Id: I28a991b19a689ffa605101656b60191bb0b9a58b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4423951
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Alex Klein <saklein@chromium.org>