dev-util/meson: Add missing dep
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
 * ERROR: sys-apps/systemd-tmpfiles-9999::chromiumos failed (configure phase):

The exec wrapper requires setuptools.

This change is already upstream, so just cherry-picking it over.

BUG=b:278728702
TEST=BOARD=arm64-generic bazel build -k --config=prebuilts/arm64-generic @portage//internal/packages/stage2/target/board/chromiumos/virtual/target-os:1_package_set

Change-Id: Ic0a57ef228ff10dc553dee9ab14c5f716cb51355
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4670295
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>