dev-python/numpy: Add missing DEPEND
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
     * ERROR: dev-python/numpy-1.19.4::portage-stable failed (compile phase):
     *   (no error message)
     *

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//dev-python/numpy

Link: https://github.com/gentoo/gentoo/pull/30469
Change-Id: I143255fde453e975e0090274b0433cd764a1524c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4401801
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>