app-emulation/qemu: Add missing ninja BDEPEND
```
ERROR: Cannot find Ninja

 * ERROR: app-emulation/qemu-7.2.8::portage-stable failed (configure phase):
 *   configure failed
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_configure
 *             environment, line 5053:  Called qemu_src_configure 'softmmu'
 *             environment, line 4914:  Called die
 * The specific snippet of code:
 *       ../configure "${conf_opts[@]}" || die "configure failed"
```

BUG=b:323026468
TEST=bazel build --config=hash_tracer @portage//host/app-emulation/qemu

Change-Id: I82ba9126ebef4d608ed89961ede03072ff412516
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/5250742
Auto-Submit: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>