dev-python/cryptography: Add missing DEPEND
This package compiles a C extension.

    /build/arm64-generic/tmp/portage/dev-python/cryptography-3.3.2/work/cryptography-3.3.2-python3_6/temp.linux-x86_64-3.6/_padding.c:22:12: fatal error: 'pyconfig.h' file not found
    #  include <pyconfig.h>
               ^~~~~~~~~~~~
    1 error generated.

The ebuild version no longer exists upstream, and the new version has
changed significantly, so I'm not pushing a fix up there right now.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//dev-python/cryptography

Change-Id: Iebe7b4846391cc66b5e1c8dc968b8867f112065c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/4401800
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>